name: PR test workflow

on: [ pull_request]

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    - name:  build step
      id: build_id
      run: |
        echo " test-pr steps"
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer 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" \
        https://api.github.com/repos/OWNER/REPO/pulls/PULL_NUMBER/comments \
        -d '{"body":"Great stuff!","commit_id":"6dcb09b5b57875f334f61aebed695e2e4193db5e","path":"file1.txt","start_line":1,"start_side":"RIGHT","line":2,"side":"RIGHT"}'
    
    - uses: Dayanandachari/actions_repo@main
      if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
      #if: ${{ success() && steps.build_id.conclusion == 'failure' }}
       
      