name: PR test workflow

on: 
#  pull_request:
#    branches: 
#      - main
 workflow_dispatch:
    inputs:
      branch:
        description: Run manually
        required: true
        default: 'main'
          
   

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    - name:  build step
    - uses: Dayanandachari/actions_repo@main
      env:
         Message: "test sucess message"
      if: ${{ success() }}
    
    
    
   

# jobs:
#   test-pr: 
#     runs-on: ubuntu-latest

#     steps: 
#     - name:  build step
#       id: build_id
#       run: |
#         echo " test-pr steps" 
#         exit 0
#     - uses: Dayanandachari/actions_repo@main
#       env:
#          GITHUB_TOKEN: ${{ github.token }}
#       with:
#         PR_number: ${{ github.event.pull_request.number}}
#         Repo_owner: ${{ github.event.owner}}
#         Repo_name: ${{ github.event.repository.name}}
#         Message: "test sucess message"
#       if: ${{ success() }}
    
#     - uses: Dayanandachari/actions_repo@main
     
#       with:
#         PR_number: ${{ github.event.pull_request.number}}
#         Repo_owner: ${{ github.event.owner}}
#         Repo_name:  ${{ github.event.repository.name}}
#         Message: "test failure message"
#       if: ${{ failure() }}