name: PR test workflow

on: [ pull_request]

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    - name:  build step
      id: build_id
      run: |
        echo " test-pr steps"
        exit 1

    - name: The demo step has failed 
      uses: Dayanandachari/actions_repo@main
      if: ${{ failure() && steps.build_id.conclusion == 'failure' }}