name: PR test workflow

on: 
 pull_request:
   branches: 
     - main

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    - name:  build step
      id: build_id
      run: |
        echo " test-pr steps" 
        exit 1
    - uses: Dayanandachari/actions_repo@main
      if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
      #if: ${{ success() && steps.build_id.conclusion == 'failure' }}

    - name: Pr message test 
      id: pr_test
      #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
      if: ${{ success() }}
      env:
       PULL_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: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" \
        https://api.github.com/repos/Dayanandachari/Github_action_repo/pulls/PULL_NUMBER/comments \
        -d '{"body":"Great stuff!","commit_id":"6efc91e","path":"file1.txt","start_line":1,"start_side":"RIGHT","line":2,"side":"RIGHT"}'
      shell: bash
       
      