name: PR test workflow

on: 
 pull_request:
   branches: 
     - main

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    # - name:  build step
    #   id: build_id
    #   run: |
    #     echo " test-pr steps" 
    #     exit 1
    # - uses: Dayanandachari/actions_repo@main
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   #if: ${{ success() && steps.build_id.conclusion == 'failure' }}
    
    # - name: Test
    #   uses: actions/github-script@0.3.0
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   with:
    #     github-token: ${{github.token}}
    #     script: |
    #       const core = require('@actions/core')
    #       const prNumber = context.payload.number;
    #       core.exportVariable('PULL_NUMBER', prNumber); 
    
    # - name: Get Pull Request Number
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   id: pr
    #   run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Pr message test 
      id: pr_test
      #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
      # if: ${{ success() }}
      env:
       PULL_NUMBER: ${{ github.event.pull_request.pull_request.url }}
      run: |
        echo $PULL_NUMBER
        # curl \
        # -X POST \
        # -H "Accept: application/vnd.github+json" \
        # -H "Authorization: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" \
        # https://api.github.com/repos/Dayanandachari/Github_action_repo/pulls/PULL_NUMBER/comments \
        # -d '{"body":"Great stuff!","commit_id":"3de9c95287ceda7f6f8528bda9195aca8c34df9b","path":"Github_action_repo/.github/workflows/file.txt","start_line":1,"start_side":"RIGHT","line":2,"side":"RIGHT"}'
      shell: bash
      
      