name: PR test workflow

on: 
 pull_request:
   branches: 
     - main

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    # - name:  build step
    #   id: build_id
    #   run: |
    #     echo " test-pr steps" 
    #     exit 1
    - uses: Dayanandachari/actions_repo@main
      id: pr_msg
      with:
        PR_number: 7
        Repo_owner: Dayanandachari
        Repo_name: Github_action_repo
        Message: "test message "
      if: ${{ success() && steps.pr_msg.conclusion == 'success' }}
       echo " test fail "
    
    # - name: Test
    #   uses: actions/github-script@0.3.0
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   with:
    #     github-token: ${{github.token}}
    #     script: |
    #       const core = require('@actions/core')
    #       const prNumber = context.payload.number;
    #       core.exportVariable('PULL_NUMBER', prNumber); 
    
    # - name: Get Pull Request Number
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   id: pr
    #   run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

    # - name: Pr message test 
    #   id: pr_test
    #   #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
    #   env:
    #    PR_NUMBER: "${{ github.event.number }}"
    #    GITHUB_TOKEN: ${{ github.token }}
    #   run: |        
    #       curl \
    #       -X POST \
    #       -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: token $GITHUB_TOKEN " \
    #       https://api.github.com/repos/Dayanandachari/Github_action_repo/issues/$PR_NUMBER/comments \
    #       -d '{"body":"**Testing** 123"}'
    #   shell: bash
      
      
# PR_number:
#     description: Repo PR number 
#     required: true
#   Repo_owner:
#     description: Owner name
#     required: true
#   Repo_name:
#     description: repo  name
#     required: true