name: PR test workflow

on: 
 pull_request:
   branches: 
     - main

jobs:
  test-pr: 
    runs-on: ubuntu-latest

    steps: 
    # - name:  build step
    #   id: build_id
    #   run: |
    #     echo " test-pr steps" 
    #     exit 1
    # - uses: Dayanandachari/actions_repo@main
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   #if: ${{ success() && steps.build_id.conclusion == 'failure' }}
    
    # - name: Test
    #   uses: actions/github-script@0.3.0
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   with:
    #     github-token: ${{github.token}}
    #     script: |
    #       const core = require('@actions/core')
    #       const prNumber = context.payload.number;
    #       core.exportVariable('PULL_NUMBER', prNumber); 
    
    # - name: Get Pull Request Number
    #   if: ${{ failure() && steps.build_id.conclusion == 'failure' }}
    #   id: pr
    #   run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Pr message test 
      id: pr_test
      #if: ${{ failure() && steps.pr_test.conclusion == 'failure' }}
      # if: ${{ success() }}
      env:
       PR_URL: "${{ github.event.pull_request.url }}"
      run: |        
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/Dayanandachari/Github_action_repo/issues/5/comments \
          -d '{"body":"**Testing** 123"}'
      shell: bash
      
      